### ISSUE TITLE
Simple triangle demo with new CLI code

### ISSUE THREAD

**Issue by michielbdejong** [ledgerloops/ledgerloops#40]
set-trust and set-balance will auto-create the two nodes involved if they don't exist yet, and if the `<to>` was not a friend of the `<from>` yet, a `from.meet(to)` will be issued, that will lead to a meet message so the to can also add the from as a friend.

**Comment by michielbdejong** [comment]
```
$ deno run -A ./src/run.ts set-trust bob charlie 10 XCH
node added to batched network simulator: charlie
bob emits message charlie meet
error: Uncaught (in promise) TypeError: probe.isVirginFor is not a function
        if (probe.isVirginFor(friend)) {
                  ^
    at file:///Users/michiel/gh/ledgerloops/ledgerloops/src/engine/probesengine.ts:140:19
    at Array.forEach (<anonymous>)
    at ProbesEngine.flushProbesQueue (file:///Users/michiel/gh/ledgerloops/ledgerloops/src/engine/probesengine.ts:135:34)
    at ProbesEngine.tryToSendProbes (file:///Users/michiel/gh/ledgerloops/ledgerloops/src/engine/probesengine.ts:157:12)
    at ProbesEngine.queueProbe (file:///Users/michiel/gh/ledgerloops/ledgerloops/src/engine/probesengine.ts:168:10)
    at file:///Users/michiel/gh/ledgerloops/ledgerloops/src/engine/probesengine.ts:175:12
    at Array.forEach (<anonymous>)
    at ProbesEngine.queueAllFloodProbes (file:///Users/michiel/gh/ledgerloops/ledgerloops/src/engine/probesengine.ts:172:20)
    at ProbesEngine.addFriend (file:///Users/michiel/gh/ledgerloops/ledgerloops/src/engine/probesengine.ts:190:10)
    at Saiga.meet (file:///Users/michiel/gh/ledgerloops/ledgerloops/src/saiga.ts:176:23)
```
